mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),

    path("<int:question_id>/choice/", views.choice, name="choice"),
    
    path("<int:question_id>/vote_reset/", views.vote_reset, name="vote_reset"),
    # ex: /polls/new/
    path("new/", views.add_question, name="new"),
]

polls/models.py
# Create your models here.
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
# Create your views here.
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.utils import timezone

from .models import Choice, Question



def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    data = {"question_list": latest_question_list,}
    return HttpResponse(render(request, 'polls/index.html', data))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})



def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def choice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'GET':
        return render(request, "polls/choice.html", {"question": question})
    elif request.method == 'POST':
        user_submitted_choice = request.POST["choice"]
        if not user_submitted_choice:
            return render(request, "polls/choice.html", {
                "question": question,
                "error_message": "Please enter a valid choice"
            })

        new_choice = Choice(
            question=question,
            choice_text=user_submitted_choice,
        )
        new_choice.save()
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))
    
def vote_reset(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    for choice in question.choice_set.all():
        choice.votes = 0
        choice.save()

    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def add_question(request):
    if request.method == 'GET':
        return render(request, "polls/question.html", {})
    elif request.method == 'POST':
        user_submitted_question = request.POST["question"]
        if not user_submitted_question:
            return render(request, "polls/question.html", {
                "error_message": "Please enter a valid question"
            })
        
        new_question = Question(
            question_text=user_submitted_question,
            pub_date=timezone.now(),
        )
        new_question.save()
    return HttpResponseRedirect(reverse("polls:index",))


    
        


        
    


    

polls/templates/polls/choice.html
<form action="{% url 'polls:choice' question.id %}" method="post">
  {% csrf_token %}
  <h1>You are adding a choice for: "{{ question.question_text }}"</h1>
  {% if error_message %}<p style="color: red"><strong>{{ error_message }}</strong></p>{% endif %}
  <label for="choice">Enter your choice: </label>
  <input type="text" value="" name="choice">
  <input type="submit" value="Add" id="choice">
</form>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <a href="{% url 'polls:choice' question.id %}">Add choice</a>
    </fieldset>
    <input type="submit" value="Vote">
    </form>
    

polls/templates/polls/index.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">
                {{ question.question_text }}
            </a>
        </li>
    {% endfor %}
    </ul>
    <a href="{% url 'polls:new' %}"> Add question </a>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/question.html
<form action="{% url 'polls:new' %}" method="post">
    {% csrf_token %}
    <h1>You are adding a new question!</h1>
    {% if error_message %}<p style="color: red"><strong>{{ error_message }}</strong></p>{% endif %}
    <label for="question">Enter your question: </label>
    <input type="text" value="" name="question">
    <input type="submit" value="Add" id="question">
</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'polls:vote_reset' question.id %}">Reset Votes</a>